package spring_boot_style.models;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * A java class representing an App_Info in the HUAWEI app store.
 */
@Entity
@Table(name = "app_info") //if omitted, will try to match same name table of this class
@Data //getter and setters generated by lombok, hibernate and jackson will use these to hydrate objects from database
public class App {

    @Id
    @NotNull
    private String appid; //C10000291, 8 digits
    private int score;
    private String title;
    private String url;
    private String thumbnailUrl;
    private String intro;
    private String developer;
    private String top5App;

    // default constructor necessary for hibernate to connect class with mysql database, avoid overriden
    public App(){}

    public App(String appid){this.appid = appid;}


}
